;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        c-electric-brace
        c-electric-colon
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-indent-line-or-region
        electric-newline-and-maybe-indent
        electric-pair-delete-pair
        end-of-visual-line
        indent-for-tab-command
        kill-visual-line
        markdown-exdent-or-delete
        ns-copy-including-secondary
        sgml-close-tag
        sgml-slash
        sgml-tag
        sh-assignment
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-star
        forward-sexp
        ido-find-file
        js2-mode-show-node
        mouse-save-then-kill
        mouse-set-region
        mouse-set-secondary
        save-and-run
        smex
        undo-tree-visualize
        ))
