(deftheme defenestrated
  "Created 2021-09-09.")

(custom-theme-set-variables
 'defenestrated
 '(initial-buffer-choice t)
 '(initial-major-mode (quote text-mode))
 '(initial-scratch-message "
")
 '(custom-safe-themes (quote ("a0feb1322de9e26a4d209d1cfa236deaf64662bb604fa513cca6a057ddf0ef64" default))))

(custom-theme-set-faces
 'defenestrated
 '(cursor ((((type graphic)) :background "#d0d060")))
 '(button ((((type graphic)) :inherit link :underline (:color "#d5d2be"))))
 '(link ((((type graphic)) :foreground "#94bff3" :underline t)))
 '(link-visited ((((type graphic)) :foreground "#3390dc" :underline t)))
 '(match ((((type graphic)) :foreground "#d5d2be" :background "#134b87")))
 '(escape-glyph ((((type graphic)) :foreground "#fe8b04" :weight bold)))
 '(fringe ((((type graphic)) :foreground "#9f9f9f" :background "#222222")))
 '(header-line ((((type graphic)) :foreground "#f6f0e1" :height 1.13 :box (:line-width 1 :color "#f6f0e1" :style nil))))
 '(highlight ((((type graphic)) :foreground "#000000" :background "#e9e9e9")))
 '(shadow ((t nil)))
 '(success ((((type graphic)) :foreground "#7fb07f" :weight bold)))
 '(error ((((type graphic)) :foreground "#ea3838" :weight bold)))
 '(warning ((((type graphic)) :foreground "#e8e815")))
 '(region ((((type graphic)) :background "#6f6f6f")))
 '(menu ((((type graphic)) :foreground "#f6f0e1" :background "#222222" :height 1.13)))
 '(tool-bar ((((type graphic)) :inherit mode-line)))
 '(scroll-bar ((((type graphic)) :background "#6f6f6f")))
 '(tooltip ((((type graphic)) :inherit variable-pitch :foreground "#0c8782" :background "#222222")))
 '(minibuffer-prompt ((((type graphic)) :inherit alect-prompt)))
 '(secondary-selection ((((type graphic)) :background "#5f5f5f")))
 '(trailing-whitespace ((((type graphic)) :background "#c64242")))
 '(vertical-border ((((type graphic)) :foreground "#d5d2be")))
 '(window-divider ((((type graphic)) :foreground "#099709")))
 '(window-divider-first-pixel ((((type graphic)) :foreground "#3cb370")))
 '(window-divider-last-pixel ((((type graphic)) :inherit window-divider-first-pixel)))
 '(alect-field-title ((((type graphic)) :foreground "#e5c900")))
 '(alect-prompt ((((type graphic)) :foreground "#dc8cc3" :weight bold)))
 '(alect-time ((((type graphic)) :foreground "#8cf1f1")))
 '(alect-author ((((type graphic)) :foreground "#dc8cc3")))
 '(alect-key ((((type graphic)) :foreground "#fa6a6e" :weight bold)))
 '(alect-selected-item ((((type graphic)) :background "#4f4f4f" :box (:line-width -1 :color "#d5d2be" :style nil))))
 '(alect-color-level-1 ((((type graphic)) :foreground "#30a5f5")))
 '(alect-color-level-2 ((((type graphic)) :foreground "#7fb07f")))
 '(alect-color-level-3 ((((type graphic)) :foreground "#db4334")))
 '(alect-color-level-4 ((((type graphic)) :foreground "#abab3a")))
 '(alect-color-level-5 ((((type graphic)) :foreground "#528d8d")))
 '(alect-color-level-6 ((((type graphic)) :foreground "#94bff3")))
 '(alect-color-level-7 ((((type graphic)) :foreground "#dc8cc3")))
 '(alect-color-level-8 ((((type graphic)) :foreground "#fe8b04")))
 '(alect-color-level-9 ((((type graphic)) :foreground "#32cd32")))
 '(alect-color-level-10 ((((type graphic)) :foreground "#fa6a6e")))
 '(alect-color-level-11 ((((type graphic)) :foreground "#8cf1f1")))
 '(alect-color-level-12 ((((type graphic)) :foreground "#be59d8")))
 '(alect-title ((((type graphic)) :foreground "#099709" :weight bold :height 1.13)))
 '(alect-title-1 ((((type graphic)) :inherit alect-color-level-1 :weight bold :height 1.13)))
 '(alect-title-2 ((((type graphic)) :inherit alect-color-level-2 :weight bold :height 1.13)))
 '(alect-title-3 ((((type graphic)) :inherit alect-color-level-3 :weight bold :height 1.13)))
 '(alect-title-4 ((((type graphic)) :inherit alect-color-level-4 :weight bold :height 1.13)))
 '(alect-title-5 ((((type graphic)) :inherit alect-color-level-5 :weight bold :height 1.13)))
 '(alect-title-6 ((((type graphic)) :inherit alect-color-level-6 :weight bold :height 1.13)))
 '(alect-title-7 ((((type graphic)) :inherit alect-color-level-7 :weight bold :height 1.13)))
 '(alect-title-8 ((((type graphic)) :inherit alect-color-level-8 :weight bold :height 1.13)))
 '(alect-button ((((type graphic)) :foreground "#f6f0e1" :background "#6f6f6f" :box (:line-width 2 :style released-button))))
 '(alect-button-pressed ((((type graphic)) :inherit alect-button :box (:line-width 2 :style pressed-button))))
 '(alect-button-mouse ((((type graphic)) :inherit highlight :box (:line-width 2 :style released-button))))
 '(alect-tab-default ((((type graphic)) :height 0.9 :box nil)))
 '(alect-tab-unselected ((((type graphic)) :inherit alect-tab-default :foreground "#8c826d" :background "#4f4f4f" :box (:line-width 1 :style released-button))))
 '(alect-tab-selected ((((type graphic)) :inherit alect-tab-unselected :foreground "#f6f0e1" :background "#5f5f5f")))
 '(alect-tab-mouse ((((type graphic)) :inherit alect-tab-default :inherit mode-line-highlight)))
 '(completions-common-part ((((type graphic)) :foreground "#8c826d")))
 '(custom-button ((((type graphic)) :inherit alect-button)))
 '(custom-button-pressed ((((type graphic)) :inherit alect-button-pressed)))
 '(custom-button-mouse ((((type graphic)) :inherit alect-button-mouse)))
 '(custom-button-unraised ((((type graphic)) :inherit alect-button :box nil)))
 '(custom-button-pressed-unraised ((((type graphic)) :inherit custom-button-unraised :underline t)))
 '(custom-documentation ((((type graphic)) :inherit font-lock-doc-face)))
 '(custom-comment ((((type graphic)) :foreground "#9f9f9f")))
 '(custom-state ((((type graphic)) :foreground "#3cb370")))
 '(custom-link ((((type graphic)) :inherit link)))
 '(custom-group-tag ((((type graphic)) :inherit alect-title-1)))
 '(custom-group-tag-1 ((((type graphic)) :inherit alect-title-2)))
 '(custom-group-subtitle ((((type graphic)) :inherit alect-title-3)))
 '(custom-face-tag ((((type graphic)) :foreground "#e81eda" :weight bold)))
 '(custom-variable-tag ((((type graphic)) :inherit font-lock-variable-name-face :weight bold)))
 '(custom-variable-button ((((type graphic)) :weight bold :underline t)))
 '(custom-visibility ((((type graphic)) :inherit link :height 0.8)))
 '(diff-context ((((type graphic)) :foreground "#d0bf8f")))
 '(diff-added ((((type graphic)) :foreground "#32cd32")))
 '(diff-changed ((((type graphic)) :foreground "#e8e815")))
 '(diff-removed ((((type graphic)) :foreground "#fa5151")))
 '(diff-indicator-added ((((type graphic)) :inherit diff-added)))
 '(diff-indicator-changed ((((type graphic)) :inherit diff-changed)))
 '(diff-indicator-removed ((((type graphic)) :inherit diff-removed)))
 '(diff-refine-added ((((type graphic)) :inherit diff-added :underline t)))
 '(diff-refine-changed ((((type graphic)) :inherit diff-changed :underline t)))
 '(diff-refine-removed ((((type graphic)) :inherit diff-removed :underline t)))
 '(diff-header ((((type graphic)) :foreground "#b0c0ff" :weight bold)))
 '(diff-hunk-header ((((type graphic)) :inherit diff-header :foreground "#099709")))
 '(diff-file-header ((((type graphic)) :inherit diff-header :foreground "#f6f0e1")))
 '(diff-function ((((type graphic)) :inherit diff-header :foreground "#62b6ea")))
 '(diff-index ((((type graphic)) :inherit diff-header :foreground "#fa5151")))
 '(diff-nonexistent ((((type graphic)) :inherit diff-header :foreground "#9f9f9f")))
 '(eldoc-highlight-function-argument ((((type graphic)) :foreground "#7fb07f" :weight bold)))
 '(font-lock-builtin-face ((((type graphic)) :foreground "#dc8cc3")))
 '(font-lock-comment-face ((t (:foreground "gray57"))))
 '(font-lock-comment-delimiter-face ((((type graphic)) :inherit font-lock-comment-face)))
 '(font-lock-constant-face ((((type graphic)) :foreground "#2fdbde")))
 '(font-lock-doc-face ((((type graphic)) :foreground "#d0bf8f" :slant italic)))
 '(font-lock-function-name-face ((((type graphic)) :foreground "#94bff3")))
 '(font-lock-keyword-face ((((type graphic)) :foreground "#30a5f5" :weight bold)))
 '(font-lock-negation-char-face ((((type graphic)) :foreground "#62b6ea")))
 '(font-lock-preprocessor-face ((((type graphic)) :foreground "#32cd32")))
 '(font-lock-string-face ((((type graphic)) :foreground "#fa6a6e")))
 '(font-lock-type-face ((((type graphic)) :foreground "#e81eda")))
 '(font-lock-variable-name-face ((((type graphic)) :foreground "#abab3a")))
 '(font-lock-warning-face ((((type graphic)) :foreground "#ea3838" :weight bold)))
 '(font-lock-regexp-grouping-backslash ((((type graphic)) :foreground "#c83029")))
 '(font-lock-regexp-grouping-construct ((((type graphic)) :foreground "#e8e815")))
 '(help-argument-name ((((type graphic)) :inherit font-lock-variable-name-face)))
 '(info-title-1 ((((type graphic)) :inherit alect-color-level-1 :height 1.5 :weight bold)))
 '(info-title-2 ((((type graphic)) :inherit alect-color-level-2 :height 1.4 :weight bold)))
 '(info-title-3 ((((type graphic)) :inherit alect-color-level-3 :height 1.3 :weight bold)))
 '(info-title-4 ((((type graphic)) :inherit alect-color-level-4 :height 1.2 :weight bold)))
 '(info-menu-header ((((type graphic)) :inherit alect-color-level-5 :height 1.1 :weight bold)))
 '(info-node ((((type graphic)) :foreground "#db4334")))
 '(info-menu-star ((((type graphic)) :foreground "#ea3838")))
 '(Info-quoted ((((type graphic)) :foreground "#f6f0e1" :weight bold)))
 '(isearch-fail ((((type graphic)) :background "#a83838")))
 '(isearch ((((type graphic)) :foreground "#d5d2be" :background "#1a63b3")))
 '(lazy-highlight ((((type graphic)) :foreground "#d5d2be" :background "#6f6f6f")))
 '(mode-line-buffer-id ((((type graphic)) :foreground "#94bff3" :weight bold)))
 '(mode-line ((((type graphic)) :foreground "#d5d2be" :background "#222222" :box (:line-width 2 :style released-button))))
 '(mode-line-inactive ((((type graphic)) :foreground "#8c826d" :background "#3f3f3f" :box (:line-width 2 :color "#222222" :style nil))))
 '(mode-line-highlight ((((type graphic)) :inherit highlight :box (:line-width 1 :style released-button))))
 '(package-help-section-name ((((type graphic)) :inherit alect-field-title)))
 '(package-name ((((type graphic)) :foreground "#94bff3")))
 '(package-status-installed ((((type graphic)) :foreground "#3cb370")))
 '(package-status-dependency ((((type graphic)) :foreground "#32cd32")))
 '(package-status-built-in ((((type graphic)) :foreground "#3390dc")))
 '(package-status-external ((((type graphic)) :foreground "#30a5f5")))
 '(package-status-incompat ((((type graphic)) :foreground "#dc8cc3")))
 '(package-status-avail-obso ((((type graphic)) :foreground "#e81eda")))
 '(package-status-disabled ((((type graphic)) :foreground "#ea3838")))
 '(package-status-unsigned ((((type graphic)) :inherit warning)))
 '(show-paren-mismatch ((((type graphic)) :foreground "#e9e9e9" :background "#ea3838")))
 '(show-paren-match ((((type graphic)) :foreground "#e9e9e9" :background "#3cb370")))
 '(vc-up-to-date-state ((((type graphic)) :foreground "#32cd32")))
 '(vc-edited-state ((((type graphic)) :foreground "#e5c900")))
 '(vc-missing-state ((((type graphic)) :foreground "#ea3838")))
 '(vc-conflict-state ((((type graphic)) :foreground "#c83029" :weight bold)))
 '(vc-locked-state ((((type graphic)) :foreground "#2fdbde")))
 '(vc-locally-added-state ((((type graphic)) :foreground "#62b6ea")))
 '(vc-needs-update-state ((((type graphic)) :foreground "#e353b9")))
 '(vc-removed-state ((((type graphic)) :foreground "#fa5151")))
 '(widget-field ((((type graphic)) :background "#4f4f4f" :box (:line-width -1 :color "#8c826d" :style nil))))
 '(widget-button ((((type graphic)) :inherit alect-button)))
 '(widget-button-pressed ((((type graphic)) :inherit alect-button-pressed)))
 '(widget-documentation ((((type graphic)) :foreground "#32cd32")))
 '(widget-inactive ((((type graphic)) :inherit shadow)))
 '(widget-single-line-field ((((type graphic)) :foreground "#f0dfaf" :inherit widget-field)))
 '(default ((t (:weight normal :family "Monaco")))))

(provide-theme 'defenestrated)
