(deftheme minimal-light-sam
  "minimal light theme.")

(custom-theme-set-faces
 'minimal-light-sam
 '(cursor ((t (:background "black" :inverse-video t))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "grey90"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "black" :weight bold))))
 '(region ((((class color) (min-colors 89)) (:background "grey90"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "grey90"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "grey20" :weight bold))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "grey20" :weight bold))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "grey20" :weight bold))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "grey20" :slant italic))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "grey20" :weight bold))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "grey20"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "grey85"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "grey50"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:inherit (font-lock-comment-face)))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "grey20" :foreground "grey40"))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "grey20" :background "grey90" :weight normal))))
 '(isearch-fail ((((class color) (min-colors 89)) (:foreground "red" :bold t))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "grey20" :background "grey90"))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground "grey20" :weight bold))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "grey20" :weight bold))))
 '(show-paren-match ((((class color) (min-colors 89)) (:background "grey90"))))
 '(show-paren-mismatch ((t (:foreground "red" :weight bold))))
 '(mode-line ((t (:background "grey90" :foreground "gray30" :inverse-video nil :box (:line-width (1 . 1) :color "white" :style unspecified) :overline "black" :underline nil))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:weight bold))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:inverse-video unspecified :overline "grey90" :underline nil :foreground "grey50" :background "white" :box (:line-width 1 :color "grey90" :style unspecified)))))
 '(hl-line ((((class color) (min-colors 89)) (:background "grey90"))))
 '(hl-line-face ((((class color) (min-colors 89)) (:background nil))))
 '(highlight-stages-negative-level-face ((((class color) (min-colors 89)) (:foreground "red"))))
 '(highlight-stages-level-1-face ((((class color) (min-colors 89)) (:background "grey98"))))
 '(highlight-stages-level-2-face ((((class color) (min-colors 89)) (:background "grey90"))))
 '(highlight-stages-level-3-face ((((class color) (min-colors 89)) (:background "grey90"))))
 '(highlight-stages-higher-level-face ((((class color) (min-colors 89)) (:background "grey90"))))
 '(org-level-1 ((((class color) (min-colors 89)) (:foreground "grey20" :height 1.6))))
 '(org-level-2 ((((class color) (min-colors 89)) (:foreground "grey20" :height 1.5))))
 '(org-level-3 ((((class color) (min-colors 89)) (:foreground "grey20" :height 1.4))))
 '(org-level-4 ((((class color) (min-colors 89)) (:foreground "grey20" :height 1.3))))
 '(org-level-5 ((((class color) (min-colors 89)) (:foreground "grey20" :height 1.2))))
 '(org-level-6 ((((class color) (min-colors 89)) (:foreground "grey20" :height 1.1))))
 '(org-level-7 ((((class color) (min-colors 89)) (:foreground "grey20"))))
 '(org-level-8 ((((class color) (min-colors 89)) (:foreground "grey20"))))
 '(outline-1 ((((class color) (min-colors 89)) (:inherit org-level-1))))
 '(outline-2 ((((class color) (min-colors 89)) (:inherit org-level-2))))
 '(outline-3 ((((class color) (min-colors 89)) (:inherit org-level-3))))
 '(outline-4 ((((class color) (min-colors 89)) (:inherit org-level-4))))
 '(outline-5 ((((class color) (min-colors 89)) (:inherit org-level-5))))
 '(outline-6 ((((class color) (min-colors 89)) (:inherit org-level-6))))
 '(outline-7 ((((class color) (min-colors 89)) (:inherit org-level-7))))
 '(outline-8 ((((class color) (min-colors 89)) (:inherit org-level-8))))
 '(org-document-title ((((class color) (min-colors 89)) (:foreground "grey20"))))
 '(org-link ((((class color) (min-colors 89)) (:background "grey98" :foreground "grey20" :underline t))))
 '(org-tag ((((class color) (min-colors 89)) (:background "grey98" :foreground "grey20"))))
 '(org-warning ((((class color) (min-colors 89)) (:background "grey90" :foreground "grey20" :weight bold))))
 '(org-todo ((((class color) (min-colors 89)) (:background "grey90" :foreground "grey20" :weight bold))))
 '(org-done ((((class color) (min-colors 89)) (:background "grey90" :foreground "grey20" :weight bold))))
 '(org-table ((((class color) (min-colors 89)) (:background "grey98"))))
 '(org-code ((((class color) (min-colors 89)) (:background "grey98"))))
 '(org-date ((((class color) (min-colors 89)) (:background "grey98" :underline t))))
 '(org-block ((((class color) (min-colors 89)) (:background "grey98"))))
 '(org-block-background ((((class color) (min-colors 89)) (:background "grey98" :foreground "grey20"))))
 '(org-block-begin-line ((((class color) (min-colors 89)) (:background "grey98" :foreground "grey85" :weight bold))))
 '(org-block-end-line ((((class color) (min-colors 89)) (:background "grey98" :foreground "grey85" :weight bold))))
 '(js2-external-variable ((((class color) (min-colors 89)) (:inherit base-faces :weight bold))))
 '(js2-function-param ((((class color) (min-colors 89)) (:inherit base-faces))))
 '(js2-instance-member ((((class color) (min-colors 89)) (:inherit base-faces))))
 '(js2-jsdoc-html-tag-delimiter ((((class color) (min-colors 89)) (:inherit base-faces))))
 '(js2-jsdoc-html-tag-name ((((class color) (min-colors 89)) (:inherit base-faces))))
 '(js2-jsdoc-tag ((((class color) (min-colors 89)) (:inherit base-faces))))
 '(js2-jsdoc-type ((((class color) (min-colors 89)) (:inherit base-faces :weight bold))))
 '(js2-jsdoc-value ((((class color) (min-colors 89)) (:inherit base-faces))))
 '(js2-magic-paren ((((class color) (min-colors 89)) (:underline t))))
 '(js2-private-function-call ((((class color) (min-colors 89)) (:inherit base-faces))))
 '(js2-private-member ((((class color) (min-colors 89)) (:inherit base-faces))))
 '(fringe ((t (:background "white" :foreground "grey50"))))
 '(auto-dim-other-buffers-face ((t (:background "grey60"))))
 '(button ((t (:inherit link :underline (:color nil :style nil) :foreground "#2222ee"))))
 '(link ((t (:foreground "#2222ee" :underline t))))
 '(widget-field ((t (:box (:line-width (1 . -1) :color "#bbbbbb") :background "#dddddd" :extend t))))
 '(default ((((class color) (min-colors 89)) (:background "white" :foreground "grey20"))))
 '(sml/global ((t (:inverse-video nil :foreground "gray50")))))

(provide-theme 'minimal-light-sam)
