(deftheme minimal-dark-sam
  "Created 2021-10-08.")

(custom-theme-set-faces
 'minimal-dark-sam
 '(cursor ((t (:inverse-video t :background "#FFFFFF"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:weight bold :foreground "#fe8b04"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:weight bold :foreground "white" :inherit (alect-prompt)))))
 '(highlight ((t (:foreground "#000000" :background "#e9e9e9"))))
 '(region ((t (:extend t :background "grey20"))))
 '(shadow ((t (:foreground "#9f9f9f"))))
 '(secondary-selection ((t (:extend t :background "grey20"))))
 '(trailing-whitespace ((t (:background "#c64242"))))
 '(font-lock-builtin-face ((t (:weight bold :foreground "grey90"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "grey16" :inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#6e8090"))))
 '(font-lock-constant-face ((t (:weight bold :foreground "grey90"))))
 '(font-lock-doc-face ((t (:slant italic :foreground "#d0bf8f" :inherit (font-lock-comment-face)))))
 '(font-lock-function-name-face ((t (:weight bold :foreground "grey90"))))
 '(font-lock-keyword-face ((t (:weight bold :foreground "grey90"))))
 '(font-lock-negation-char-face ((t (:foreground "#62b6ea"))))
 '(font-lock-preprocessor-face ((t (:foreground "#32cd32"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#c83029"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#e8e815"))))
 '(font-lock-string-face ((t (:foreground "grey70"))))
 '(font-lock-type-face ((t (:slant italic :foreground "grey90"))))
 '(font-lock-variable-name-face ((t (:foreground "grey90"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#ea3838"))))
 '(button ((t (:underline (:color "#d5d2be" :style line) :inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#94bff3"))))
 '(link-visited ((t (:underline (:color foreground-color :style line) :foreground "#3390dc"))))
 '(fringe ((t (:background "black" :foreground "grey90"))))
 '(header-line ((t (:height 1.13 :box (:line-width (1 . 1) :color "#f6f0e1" :style nil) :foreground "#f6f0e1"))))
 '(tooltip ((t (:foreground "#0c8782" :background "#222222" :inherit (variable-pitch)))))
 '(mode-line ((t (:underline nil :overline "grey40" :box (:line-width (1 . 1) :color "white" :style unspecified) :inverse-video nil :foreground "white" :background "black"))))
 '(mode-line-buffer-id ((t (:weight bold :inherit sml/filename))))
 '(mode-line-emphasis ((t (:foreground "white" :weight bold))))
 '(mode-line-highlight ((t (:inherit highlight :box (:line-width (1 . 1) :style released-button)))))
 '(mode-line-inactive ((t (:background "grey40" :foreground "grey90" :inverse-video nil :box (:line-width (1 . 1) :color "grey40" :style unspecified) :overline "grey80" :underline nil))))
 '(isearch ((t (:weight normal :foreground "grey90" :background "grey20"))))
 '(isearch-fail ((t (:weight bold :foreground "red" :background "#a83838"))))
 '(lazy-highlight ((t (:foreground "grey90" :background "grey20"))))
 '(match ((t (:foreground "#d5d2be" :background "#134b87"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(auto-dim-other-buffers-face ((t (:background "grey30"))))
 '(default ((t (:family "Inconsolata" :foundry "nil" :width normal :height 140 :weight normal :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "grey90" :background "black" :stipple nil :inherit nil))))
 '(company-preview ((t (:background "#0033bb" :foreground "white"))))
 '(sml/filename ((t (:weight bold :foreground "white" :inherit sml/global))))
 '(sml/global ((t (:inverse-video nil :foreground "gray50"))))
 '(sml/line-number ((t (:inherit sml/modes :foreground "grey80" :weight bold))))
 '(sml/numbers-separator ((t (:inherit (sml/col-number))))))

(provide-theme 'minimal-dark-sam)
