(deftheme sam-dark
  "Created 2021-10-07.")

(custom-theme-set-faces
 'sam-dark
 '(cursor ((t (:background "#FFFFFF"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:weight bold :foreground "#fe8b04"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:inherit (alect-prompt)))))
 '(highlight ((t (:foreground "#000000" :background "#e9e9e9"))))
 '(region ((t (:extend t :background "#6f6f6f"))))
 '(shadow ((t (:foreground "#9f9f9f"))))
 '(secondary-selection ((t (:extend t :background "#5f5f5f"))))
 '(trailing-whitespace ((t (:background "#c64242"))))
 '(font-lock-builtin-face ((t (:foreground "#dc8cc3"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#6e8090"))))
 '(font-lock-constant-face ((t (:foreground "#2fdbde"))))
 '(font-lock-doc-face ((t (:slant italic :foreground "#d0bf8f"))))
 '(font-lock-function-name-face ((t (:foreground "#94bff3"))))
 '(font-lock-keyword-face ((t (:weight bold :foreground "#30a5f5"))))
 '(font-lock-negation-char-face ((t (:foreground "#62b6ea"))))
 '(font-lock-preprocessor-face ((t (:foreground "#32cd32"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#c83029"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#e8e815"))))
 '(font-lock-string-face ((t (:foreground "#fa6a6e"))))
 '(font-lock-type-face ((t (:foreground "#e81eda"))))
 '(font-lock-variable-name-face ((t (:foreground "#abab3a"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#ea3838"))))
 '(button ((t (:underline (:color "#d5d2be" :style line) :inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#94bff3"))))
 '(link-visited ((t (:underline (:color foreground-color :style line) :foreground "#3390dc"))))
 '(fringe ((t (:foreground "#9f9f9f" :background "#393c40"))))
 '(header-line ((t (:height 1.13 :box (:line-width (1 . 1) :color "#f6f0e1" :style nil) :foreground "#f6f0e1"))))
 '(tooltip ((t (:foreground "#0c8782" :background "#222222" :inherit (variable-pitch)))))
 '(mode-line ((t (:box (:line-width (2 . 2) :color nil :style released-button) :inverse-video nil :foreground "gray60" :background "black"))))
 '(mode-line-buffer-id ((t (:weight bold :inherit (sml/filename)))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:box (:line-width (1 . 1) :color nil :style released-button) :inherit (highlight)))))
 '(mode-line-inactive ((t (:box (:line-width (2 . 2) :color "#222222" :style nil) :inverse-video nil :foreground "gray60" :background "#404045"))))
 '(isearch ((t (:foreground "#d5d2be" :background "#1a63b3"))))
 '(isearch-fail ((t (:background "#a83838"))))
 '(lazy-highlight ((t (:foreground "#d5d2be" :background "#6f6f6f"))))
 '(match ((t (:foreground "#d5d2be" :background "#134b87"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(default ((t (:family "Inconsolata" :foundry "nil" :width normal :height 140 :weight normal :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#DCDCDC" :background "#393c40" :stipple nil :inherit nil))))
 '(auto-dim-other-buffers-face ((t (:background "gray35")))))

(provide-theme 'sam-dark)
