
;; ----- smex-history -----
(
 customize-face
 load-theme
 list-faces-display
 customize-create-theme
 scroll-bar-mode
 describe-face
 arduino-mode
)

;; ----- smex-data -----
(
 (ispell-buffer . 1)
 (write-file . 64)
 (paredit-mode . 6)
 (js2-mode . 2)
 (jsx-mode . 2)
 (customize-set-variable . 6)
 (eval-last-sexp . 2)
 (ansi-term . 2)
 (package-install . 19)
 (delete-whitespace-rectangle . 2)
 (describe-function . 3)
 (clear-rectangle . 1)
 (hlt-unhighlight-all-prop . 1)
 (hlt-unhighlight-region . 1)
 (revert-buffer . 3)
 (read-only-mode . 1)
 (yas-reload-all . 3)
 (recover-this-file . 1)
 (query-replace . 16)
 (adaptive-wrap-prefix-mode . 6)
 (replace-string . 26)
 (prettify-symbols-mode . 2)
 (sgml-pretty-print . 2)
 (yas-insert-snippet . 2)
 (yas-new-snippet . 3)
 (yas-visit-snippet-file . 7)
 (html-mode . 2)
 (web-mode . 3)
 (pwd . 2)
 (query-replace-regexp . 15)
 (replace-regexp . 63)
 (describe-key . 19)
 (processing-mode . 2)
 (jedi:install-server . 7)
 (server-start . 1)
 (erc . 1)
 (indent-region . 2)
 (align-regexp . 2)
 (package-list-packages . 4)
 (package-autoremove . 1)
 (package-initialize . 2)
 (company-mode . 5)
 (package-delete . 7)
 (company-jedi . 2)
 (jedi-mode . 3)
 (delete-horizontal-space . 1)
 (delete-trailing-whitespace . 1)
 (quit-window . 1)
 (customize-face . 40)
 (set-variable . 1)
 (eval-expression . 2)
 (linum-mode . 2)
 (re-builder . 3)
 (string-inflection-kebab-case . 11)
 (skewer-mode . 2)
 (run-skewer . 3)
 (skewer-html-mode . 2)
 (list-skewer-clients . 1)
 (text-mode . 4)
 (grep . 1)
 (find-name-dired . 1)
 (markdown-mode . 1)
 (livedown-preview . 2)
 (eval-buffer . 1)
 (package-install-selected-packages . 2)
 (whitespace-mode . 10)
 (platformio-build . 3)
 (global-linum-mode . 1)
 (customize-variable . 4)
 (customize-mode . 6)
 (global-set-key . 5)
 (hs-toggle-hiding . 3)
 (global-unset-key . 3)
 (local-unset-key . 7)
 (local-set-key . 1)
 (auto-dim-other-buffers-mode . 1)
 (platformio-mode . 13)
 (arduino-mode . 20)
 (platformio-clean . 1)
 (customize-group . 2)
 (describe-variable . 1)
 (hs-show-all . 2)
 (hs-hide-all . 7)
 (customize-themes . 4)
 (custom-theme-visit-theme . 5)
 (scroll-other-window . 1)
 (scroll-all-mode . 2)
 (hs-minor-mode . 2)
 (c++-mode . 4)
 (c-toggle-comment-style . 3)
 (hs-show-block . 2)
 (toggle-scroll-bar . 1)
 (sp-previous-sexp . 3)
 (load-theme . 33)
 (customize-unsaved . 1)
 (list-colors-display . 1)
 (describe-face . 4)
 (list-faces-display . 5)
 (custom-theme-merge-theme . 1)
 (custom-theme-save . 1)
 (customize-create-theme . 6)
 (mwheel-scroll . 1)
 (scroll-bar-mode . 1)
)
