
;; ----- smex-history -----
(
 platformio-mode
 arduino-mode
 write-file
 customize-face
 auto-dim-other-buffers-mode
 package-install
 replace-regexp
)

;; ----- smex-data -----
(
 (ispell-buffer . 1)
 (write-file . 62)
 (paredit-mode . 6)
 (js2-mode . 2)
 (jsx-mode . 2)
 (customize-set-variable . 1)
 (eval-last-sexp . 2)
 (ansi-term . 2)
 (package-install . 15)
 (delete-whitespace-rectangle . 2)
 (describe-function . 3)
 (clear-rectangle . 1)
 (hlt-unhighlight-all-prop . 1)
 (hlt-unhighlight-region . 1)
 (revert-buffer . 3)
 (read-only-mode . 1)
 (yas-reload-all . 2)
 (recover-this-file . 1)
 (query-replace . 13)
 (adaptive-wrap-prefix-mode . 6)
 (replace-string . 24)
 (prettify-symbols-mode . 2)
 (sgml-pretty-print . 2)
 (yas-insert-snippet . 2)
 (yas-new-snippet . 2)
 (yas-visit-snippet-file . 2)
 (html-mode . 2)
 (web-mode . 3)
 (pwd . 2)
 (query-replace-regexp . 5)
 (replace-regexp . 60)
 (describe-key . 9)
 (processing-mode . 1)
 (jedi:install-server . 7)
 (server-start . 1)
 (erc . 1)
 (indent-region . 2)
 (align-regexp . 2)
 (package-list-packages . 2)
 (package-autoremove . 1)
 (package-initialize . 2)
 (company-mode . 3)
 (package-delete . 7)
 (company-jedi . 2)
 (jedi-mode . 3)
 (delete-horizontal-space . 1)
 (delete-trailing-whitespace . 1)
 (quit-window . 1)
 (customize-face . 12)
 (set-variable . 1)
 (eval-expression . 2)
 (linum-mode . 2)
 (re-builder . 1)
 (string-inflection-kebab-case . 11)
 (skewer-mode . 2)
 (run-skewer . 3)
 (skewer-html-mode . 2)
 (list-skewer-clients . 1)
 (text-mode . 2)
 (grep . 1)
 (find-name-dired . 1)
 (markdown-mode . 1)
 (livedown-preview . 2)
 (eval-buffer . 1)
 (package-install-selected-packages . 2)
 (whitespace-mode . 10)
 (platformio-build . 3)
 (global-linum-mode . 1)
 (customize-variable . 1)
 (customize-mode . 5)
 (global-set-key . 2)
 (hs-toggle-hiding . 1)
 (global-unset-key . 2)
 (local-unset-key . 1)
 (local-set-key . 1)
 (auto-dim-other-buffers-mode . 1)
 (platformio-mode . 7)
 (arduino-mode . 5)
 (platformio-clean . 1)
)
